### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Lsmorales94** [Lsmorales94/practicaApp#5]
Opciones para iniciar sesión en la aplicación diseño inicial

**Comment by Lsmorales94** [comment]
Iniciar con un bosquejo de la parte visual para el usuario

**Comment by STEVENLAKES** [comment]
Login
![Login](https://user-images.githubusercontent.com/48501359/56072413-2c1d4180-5d5c-11e9-84fd-74a79329986d.jpg)
